spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: jiangfan96.
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 80